### ISSUE TITLE
Gene-stealer Cult Image Failed Unsupported Format

### ISSUE THREAD

**Issue by KitsuneAkaiyuki** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#33]
So, downloaded the new update, and found 2 issues, one with a Ridge Runner w/ Mortar, and one with a Metamorph Leader w/ Bonesword.

Ridgerunner is missing a piece on the roof, a person coming out of a hatch
metamorph's bonesword appears to be in an unsupported format
![runner, and metamorph](https://user-images.githubusercontent.com/102726472/163735611-23da4054-d845-41df-95e3-09e4806d4ee2.png)

**Comment by Malice-red** [comment]
Model fixed in latest patch

**Comment by KitsuneAkaiyuki** [comment]
is this patch you mention not released yet? as I just downloaded everything again, and these two models still have issues

**Comment by Malice-red** [comment]
> is this patch you mention not released yet? as I just downloaded everything again, and these two models still have issues

Sorry, this sounded a lot like another issue that was recently resolved with the GSC, this is still happening on the latest version.
